---
- name: Wait for ssh to be ready
  local_action:
    module: wait_for
    port: "22"
    host: "{{ inventory_hostname }}"
    search_regex: OpenSSH
    delay: 1

- name: Initialize interface_list
  set_fact:
    interface_list: []

- name: List the ansible interfaces
  set_fact:
    interface_list: "{{ interface_list }} + ['{{ item }}']"
  when: item.find(interface_regex) > -1
  with_items: "{{ ansible_interfaces }}"

- name: Display interface list when verbosity >= 1, skip otherwise
  debug: msg="{{ interface_list }}" verbosity=1

- name: Ensure lldpad service is running
  become: true
  service:
    name: lldpad
    state: started

- name: Execute topology collector
  topology: system_name={{ inventory_hostname }} interface={{ item }}
  with_items: "{{ interface_list }}"
  register: interface_json
  ignore_errors: yes

- name: Display topology json when verbosity >= 1, skip otherwise
  debug: msg="{{ interface_json }}" verbosity=1

- name: Create output file name
  set_fact: json_outfile={{ temp_dir }}/{{ inventory_hostname }}.json

- name: Write the json output
  template: src=output.j2 dest={{ json_outfile }}
  delegate_to: 127.0.0.1

- name: Print out the contents of the json output file when verbosity >= 1, skip otherwise
  debug: msg="{{ lookup('file', '{{ json_outfile }}') }}" verbosity=1
