- project:
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py27
        - openstack-tox-py36
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py27
        - openstack-tox-py36
