---
- name: Wait for {{ inventory_hostname }} ssh to be ready
  local_action:
    module: wait_for
    port: "22"
    host: "{{ inventory_hostname }}"
    search_regex: OpenSSH
    delay: 1

- name: Get a list of the matching interfaces on {{ inventory_hostname }}
  interfaces: state=UP regex={{ interface_regex }}
  register: interface_list

- name: Display full output
  debug: msg="{{ interface_list }}" verbosity=3

- name: Display interface_list
  debug: msg="{{ interface_list.matches }}" verbosity=2

- name: Execute lldp_neighbor_tlv
  topology: system_name={{ inventory_hostname}} interface={{ item }}
  with_items: "{{ interface_list.matches }}"
  register: neighbor_tlv

- name: Display neighbor_tlv
  debug: msg="{{ item }}" verbosity=2
  with_items: "{{ neighbor_tlv.results }}"

- name: Create output file name
  set_fact: report_outfile={{ output_dir }}/collector.{{ ansible_date_time.date }}@{{ansible_date_time.time}}.json

- name: Write out a file of TLVs
  template: src=output.j2 dest={{ report_outfile }}
  with_items: "{{ neighbor_tlv.results }}"
  delegate_to: 127.0.0.1

- name: Print out the contents of the file
  debug: msg="{{ lookup('file', '{{ report_outfile }}') }}"
