---
- name: Run nova command on {{ inventory_hostname }}
  shell: nova hypervisor-list
  environment: "{{ osc_env }}"
  register: hlist
  remote_user: root

- name: Print hypervisor list
  debug: msg="{{ hlist }}" verbosity=1

- name: Write to compute_hosts file
  template: src=compute_hosts.j2 dest=./compute_hosts
  delegate_to: localhost
