---
- name: Wait for {{ inventory_hostname }} ssh to be ready
  local_action:
    module: wait_for
    port: "22"
    host: "{{ inventory_hostname }}"
    search_regex: OpenSSH
    delay: 1
  remote_user: root

- name: Execute lldp_neighbor_tlv
  lldp_neighbor_tlv: interface=eno1
  register: neighbor_tlv
  remote_user: root

- name: Display neighbor_tlv
  debug: msg="{{ neighbor_tlv }}"

- name: Display stdout output
  debug: msg="{{ neighbor_tlv.stdout }}"
