---
- name: Run the whole thing
  hosts: localhost
  gather_facts: no
  remote_user: "{{ remote_usr }}"
  vars_files: ["user_vars.yml"]

  tasks:
  - name: Clean up tmp files from previous runs
    file: path="{{ temp_dir }}" state=absent

  - name: Make sure tmp dir exists
    file: path="{{ temp_dir }}" state=directory

- name: Run topology playbook
  import_playbook: topology.yml

- name: Run report playbook
  import_playbook: report.yml
